// Generated by wp-next — do not edit manually
import './globals.css';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: {
    template: '%s | My Blog',
    default: 'My Blog',
  },
  description: 'A WordPress-powered blog migrated to Next.js by wp-next',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className="min-h-screen bg-white text-gray-900 antialiased">
        <header className="border-b">
          <nav className="mx-auto max-w-5xl px-4 h-16 flex items-center gap-6">
            <Link href="/" className="font-bold text-xl">
              My Blog
            </Link>
            <Link href="/posts" className="text-sm hover:text-blue-600">
              Posts
            </Link>
            <Link href="/pages" className="text-sm hover:text-blue-600">
              Pages
            </Link>
          </nav>
        </header>

        {children}

        <footer className="border-t mt-16">
          <div className="mx-auto max-w-5xl px-4 py-8 text-sm text-gray-500">
            Powered by wp-next
          </div>
        </footer>
      </body>
    </html>
  );
}
