// Generated by wp-next — do not edit manually
// List page: paginated post listing
import { client } from '@/lib/wp-client';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Latest posts',
};

interface Props {
  searchParams: Promise<{ page?: string }>;
}

export default async function PostListPage({ searchParams }: Props) {
  const { page: pageParam } = await searchParams;
  const page = Number(pageParam) || 1;
  const { data: posts, totalPages } = await client.fetchPosts({
    type: '#postType',
    page,
    perPage: 10,
  });

  return (
    <main className="mx-auto max-w-3xl px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Blog</h1>

      <div className="space-y-8">
        {posts.map((post) => (
          <article key={post.slug} className="border-b pb-8">
            <Link href={`/#routeDir/${post.slug}`}>
              <h2 className="text-2xl font-semibold hover:text-blue-600 mb-2">
                {post.title}
              </h2>
            </Link>
            <p className="text-gray-600 mb-2">{post.excerpt}</p>
            <time className="text-sm text-gray-400">{post.date}</time>
          </article>
        ))}
      </div>

      {totalPages > 1 && (
        <nav className="flex gap-4 mt-8 justify-center">
          {page > 1 && (
            <Link href={`?page=${page - 1}`} className="text-blue-600">
              ← Previous
            </Link>
          )}
          <span className="text-gray-500">
            Page {page} of {totalPages}
          </span>
          {page < totalPages && (
            <Link href={`?page=${page + 1}`} className="text-blue-600">
              Next →
            </Link>
          )}
        </nav>
      )}
    </main>
  );
}
