// Generated by wp-next — do not edit manually
// Posts: SSG with generateStaticParams + ISR
import { client } from '@/lib/wp-client';
import { ContentRenderer, codeProcessor, imageProcessor, linkProcessor } from '@wp-next-public/react';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

export const revalidate = 3600; // ISR: 1 hour
export const dynamicParams = true;

export async function generateStaticParams() {
  const posts = await client.fetchPosts({ perPage: 100 });
  return posts.data.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = await client.fetchPost(slug);
  if (!post) return { title: 'Not Found' };

  return {
    title: post.seoTitle || post.title,
    description: post.seoDescription || post.excerpt,
    openGraph: post.ogImage
      ? { images: [{ url: post.ogImage }] }
      : undefined,
    alternates: {
      canonical: post.canonicalUrl,
    },
  };
}

interface Props {
  params: Promise<{ slug: string }>;
}

export default async function PostPage({ params }: Props) {
  const { slug } = await params;
  const post = await client.fetchPost(slug);
  if (!post) notFound();

  return (
    <article className="mx-auto max-w-3xl px-4 py-8">
      <header className="mb-8">
        <h1 className="text-4xl font-bold mb-4">{post.title}</h1>
        <div className="flex items-center gap-4 text-sm text-gray-600">
          <time dateTime={post.date}>
            {new Date(post.date).toLocaleDateString('zh-CN')}
          </time>
          {post.categories?.map((cat) => (
            <a
              key={cat.slug}
              href={`/category/${cat.slug}`}
              className="text-blue-600 hover:underline"
            >
              {cat.name}
            </a>
          ))}
        </div>
      </header>

      <ContentRenderer
        html={post.content}
        processors={[codeProcessor, imageProcessor, linkProcessor]}
        className="prose prose-lg max-w-none"
      />
    </article>
  );
}
