# #projectName

Generated by `wp-next init`.

## Development

```bash
pnpm install
pnpm dev
```

## WordPress webhook

This project includes a signed WordPress webhook receiver:

```text
POST /api/wp-next/webhook
```

Configure the same secret in `.env.local` and in the WordPress `wp-next-connector` plugin:

```bash
cp .env.example .env.local
```

Supported events:

- `test`
- `post_published`
- `post_updated`
- `post_deleted`
- `page_published`
- `page_updated`
- `page_deleted`

The receiver expects `X-WP-Next-Signature: sha256=<hex>` where the hex digest is HMAC-SHA256 of the raw JSON body using `WP_NEXT_WEBHOOK_SECRET`.
