/* Generated by wp-next — do not edit manually */

// Post types
export interface Post {
  id: number;
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  date: string;
  modified: string;
  featuredMedia?: { url: string; alt: string };
  categories?: Term[];
  tags?: Term[];
  author?: Author;
  seoTitle?: string;
  seoDescription?: string;
  canonicalUrl?: string;
  ogImage?: string;
}

export interface Page extends Post {
  parent?: number;
}

export interface Term {
  id: number;
  name: string;
  slug: string;
  count?: number;
}

export interface Author {
  id: number;
  name: string;
  slug: string;
  avatar?: string;
  description?: string;
}
