// Generated by wp-next — do not edit manually
// WordPress data client — connects to your WP backend

import { createWpClient } from '@wp-next-public/core';

const baseUrl = process.env.WP_URL || '#wpUrl';
const mode = '#dataMode' as const;

export const client = createWpClient({
  baseUrl,
  mode,
  hmac:
    mode === 'hmac' && process.env.WP_HMAC_SECRET
      ? { secret: process.env.WP_HMAC_SECRET }
      : undefined,
});
